apiVersion: v1
kind: List
items:
- apiVersion: cluster.k8s.io/v1alpha3
  kind: Machine
  metadata:
    labels:
      set: master
    name: master-0
    namespace: weavek8sops
  spec:
    providerSpec:
      value:
        apiVersion: baremetalproviderspec/v1alpha3
        kind: BareMetalMachineProviderSpec
        private:
          address: 10.0.0.25
          port: 22
        public:
          address: 13.229.104.32
          port: 22
- apiVersion: cluster.k8s.io/v1alpha3
  kind: Machine
  metadata:
    labels:
      set: worker
    name: worker-0
    namespace: weavek8sops
  spec:
    providerSpec:
      value:
        apiVersion: baremetalproviderspec/v1alpha3
        kind: BareMetalMachineProviderSpec
        private:
          address: 10.0.0.26 
          port: 22
        public:
          address: 18.140.62.230
          port: 22
