apiVersion: cluster.x-k8s.io/v1alpha3
kind: Machine
metadata:
  labels:
    set: master
  name: master-1
spec:
  clusterName: example
  bootstrap: {}
  version: 1.18.15
  infrastructureRef:
    apiVersion: cluster.weave.works/v1alpha3
    kind: ExistingInfraMachine
    name: master-1
---
apiVersion: cluster.weave.works/v1alpha3
kind: ExistingInfraMachine
metadata:
  name: master-1
spec:
  private:
    address: 10.0.0.25
    port: 22
  public:
    address: 13.250.48.213
    port: 22
---
apiVersion: cluster.x-k8s.io/v1alpha3
kind: Machine
metadata:
  labels:
    set: worker
  name: worker-1
spec:
  clusterName: example
  bootstrap: {}
  version: 1.18.15
  infrastructureRef:
    apiVersion: cluster.weave.works/v1alpha3
    kind: ExistingInfraMachine
    name: worker-1
---
apiVersion: cluster.weave.works/v1alpha3
kind: ExistingInfraMachine
metadata:
  name: worker-1
spec:
  private:
    address: 10.0.0.26 
    port: 22
  public:
    address: 54.169.115.97
    port: 22
